basePath: /
host: localhost:8080
info:
  contact: {}
  description: API documentation for the Gin application.
  title: Gin API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
